#!/bin/sh

mkdir -p checkout
cd checkout

if [ -d "clipper" ]; then
    echo "Found clipper"
else
    echo "Checking out clipper"
  curl -L http://www.ysbl.york.ac.uk/jsd523/clipper-gemmi-wrapper-20240123.tar.gz -o clipper-gemmi-wrapper.tar.gz
    echo "Unpacking fftw-2.1.5"
    tar xf clipper-gemmi-wrapper.tar.gz
    mv clipper-gemmi-wrapper clipper

#    echo
#    bzr checkout --lightweight  http://fg.oisin.rc-harwell.ac.uk/anonscm/bzr/clipper/trunk/ clipper

    echo
fi 

if [ -d "gemmi" ]; then
  echo "Found gemmi"
else
    echo "Checking out gemmi"
    git clone https://github.com/project-gemmi/gemmi.git gemmi
    cd gemmi
    git checkout v0.6.4
    cd ..
    echo
fi

if [ -d "mmdb2" ]; then
    echo "Found mmdb2"
else
echo "Checking out mmdb2"
bzr checkout --lightweight  http://fg.oisin.rc-harwell.ac.uk/anonscm/bzr/mmdb2/trunk/ mmdb2
echo
fi

if [ -d "libccp4" ]; then
    echo "Found libccp4"
else
    echo "Checking out libccp4"
    bzr checkout --lightweight  http://fg.oisin.rc-harwell.ac.uk/anonscm/bzr/libccp4/trunk/ libccp4
    echo
fi 



if [ -d "fftw-2.1.5" ]; then
    echo "Found fftw-2.1.5"
else

echo "Downloading out fftw-2.1.5"
curl -L http://www.fftw.org/fftw-2.1.5.tar.gz -o fftw-2.1.5.tar.gz
echo
echo "Unpacking fftw-2.1.5"
tar xf fftw-2.1.5.tar.gz
echo
fi

cd ..